#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"
#include <wx/wx.h>
#include <vector>
#include <iostream>
#include <random>
#include <memory>
#include <cstdlib>
#include <cstdio>
#include <ctime>
#include <cmath>
#include <wx/dcbuffer.h>
//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_button1_click( wxCommandEvent& event );
		void m_button2_click( wxCommandEvent& event );
		void m_button3_click( wxCommandEvent& event );
		void m_button4_click( wxCommandEvent& event );
		void m_cb_color_click( wxCommandEvent& event );
		void m_s_rotation_onscroll( wxScrollEvent& event );
		void m_s_tilt_onscroll( wxScrollEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
	wxBitmap m_bitmap;
	wxImage m_image;
	void Draw(float points[100][3]);
	void Repaint();
	void PrepareData(int);
	double rotation = 0, tilt = 0;
	bool ShowColor = false;
};

#endif // __GUIMyFrame1__
